name: all-tests-local-dev

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - test-automation-migration-and-github-workflows

concurrency:
  group: ${{ github.workflow }}

jobs:
  all-tests-local-dev:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Change Directory to main project
        run: cd ..
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Start Frontend on Dev environment
        run: npm run start:dev
      - name: Run Playwright tests
        run: xvfb-run --auto-servernum -- npm run playwright:test
        env:
          ENVIRONMENT_URL: http://127.0.0.1:3000
          HEADLESS_MODE: ${{ vars.HEADLESS_MODE}}
          METAMASK_SETUP_PRIVATE_KEY: ${{secrets.METAMASK_SETUP_PRIVATE_KEY}}
          METAMASK_TEST_ONE_PRIVATE_KEY: ${{secrets.METAMASK_TEST_ONE_PRIVATE_KEY}}
          METAMASK_TEST_TWO_PRIVATE_KEY: ${{secrets.METAMASK_TEST_TWO_PRIVATE_KEY}}
          METAMASK_SETUP_PASSWORD: ${{secrets.METAMASK_SETUP_PASSWORD}}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: fathom/playwright-tests/test-report/
          retention-days: 30