name: smoke-tests-local-dev

on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_run_complete:
        description: 'Qase Run autocomplete'
        required: true
  pull_request:
    branches:
      - dev

concurrency:
  group: ci-dev

jobs:
  smoke-tests-local-dev:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: qase-tms/qase-link-run@main
        env:
          QASE_API_TOKEN: ${{ env.QASE_API_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get the branch name
        id: get_branch_name
        run: |
            if [ "${{ github.event_name }}" == "pull_request" ]; then
              echo "BRANCH_NAME=$(echo ${{ github.head_ref }})" >> $GITHUB_ENV
            else
              echo "BRANCH_NAME=$(echo ${{ github.ref_name }})" >> $GITHUB_ENV
            fi
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Start Frontend on Dev environment in background
        run: npm run start:dev &
      - name: Wait for server to start
        run: sleep 40
      - name: Run Playwright tests
        run: QASE_MODE=testops xvfb-run --auto-servernum -- npm run playwright:test:smoke
        env:
          ENVIRONMENT_URL: http://127.0.0.1:3000
          HEADLESS_MODE: ${{ vars.HEADLESS_MODE}}
          METAMASK_SETUP_PRIVATE_KEY: ${{secrets.METAMASK_SETUP_PRIVATE_KEY}}
          METAMASK_TEST_ONE_PRIVATE_KEY: ${{secrets.METAMASK_TEST_ONE_PRIVATE_KEY}}
          METAMASK_TEST_TWO_PRIVATE_KEY: ${{secrets.METAMASK_TEST_TWO_PRIVATE_KEY}}
          METAMASK_SETUP_PASSWORD: ${{secrets.METAMASK_SETUP_PASSWORD}}
          QASE_PW_API_TOKEN: ${{secrets.QASE_PW_API_TOKEN}}
          QASE_TESTOPS_API_TOKEN: ${{secrets.QASE_TESTOPS_API_TOKEN}}
          QASE_TEST_RUN_NAME: CI Automation Tests Run - Smoke at branch ${{ env.BRANCH_NAME }}
          QASE_ENVIRONMENT: local-dev-apothem
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: playwright-tests/test-report/
          retention-days: 30
      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: playwright-tests/test-report/results.json
